import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import EditorLayoutProvider from "@/components/EditorLayoutProvider";
import Providers from "@/components/providers";

const jetbrains = JetBrains_Mono({
	variable: "--font-jetbrains",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body className={`${jetbrains.variable} antialiased`}>
				<Providers>
					<EditorLayoutProvider>{children}</EditorLayoutProvider>
				</Providers>
			</body>
		</html>
	);
}
